input:
  category: "SURFACE"
  base_url: "https://legacy.bas.ac.uk/met/READER/ANTARCTIC_METEOROLOGICAL_DATA/SURFACE/"
  files:
    - "Byrd_surface.dat"
  file_extension: ".dat"

output:
  folder: "data/"
  split: "monthly"

schedule:
  enabled: false
  interval_seconds: 30

state:
  file: "data/processed_files.json"


metadata:
  station:
    latitude:
      standard_name: "latitude"
      long_name: "latitude"
      units: "degrees_north"

    longitude:
      standard_name: "longitude"
      long_name: "longitude"
      units: "degrees_east"

    height:
      standard_name: "height"
      long_name: "station height"
      units: "m"
      positive: "up"
      axis: "Z"

  global:
    title: "Antarctic Meteorological Data"
    summary: "Historical Antarctic meteorological observations collected from staffed surface stations, automatic weather stations, and upper air sounding stations"
    keywords: "Antarctica, meteorology, surface observations, polar climate, upper air sounding, temperature, pressure, wind speed, weather station"
    license: "http://spdx.org/licenses/CC-BY-4.0"
    spatial_representation: "station collection"
    geospatial_coverage: "discrete points"
    institution: "British Antarctic Survey"
  
    creator_type: "person"
    creator_name: "Steve Colwell"
    creator_email: "src@bas.ac.uk"
    creator_url: "https://www.bas.ac.uk/profile/src/"
    
    publisher_type: "institution"
    publisher_name: "Norwegian Meteorological Institute/Arctic Data Centre (NO/MET/ADC)"
    publisher_email: "adc-support@met.no"
    publisher_url: "https://adc.met.no/"

    Conventions: "CF-1.11, ACDD-1.3"
    featureType: "timeSeries"
    source: "Surface meteorological observations collected from Antarctic research stations"
    comment: "Historical Antarctic meteorological observations. Missing values and observational completeness may vary"
    project: "READER Antarctic Data for Environmental Research"
    history: "Dataset is continuously updated as new observations become available" 

  variables:
    temperature:
      long_name: "Air temperature"
      standard_name: "air_temperature"
      units: "K"
      units_metadata: "temperature: on_ scale"
      coverage_content_type: "physicalMeasurement"

    sea_pressure:
      long_name: "Sea level pressure"
      standard_name: "air_pressure_at_sea_level"
      units: "Pa"
      coverage_content_type: "physicalMeasurement"

    station_pressure:
      long_name: "Station pressure"
      standard_name: "air_pressure"
      units: "Pa"
      coverage_content_type: "physicalMeasurement"

    wind_speed:
      long_name: "Wind speed"
      standard_name: "wind_speed"
      units: "m s-1"
      coverage_content_type: "physicalMeasurement"

    wind_direction:
      long_name: "Wind direction"
      standard_name: "wind_from_direction"
      units: "degree"
      coverage_content_type: "physicalMeasurement"
